name: Development checks

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.x
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: v1-npm-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: v1-npm-deps-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
      - name: Run tests
        run: yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.x
        registry-url: "https://npm.pkg.github.com"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: v1-npm-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: v1-npm-deps-
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
    - name: Run linter
      run: yarn lint
